language: node_js
node_js: 16.10.0
before_install:
- cd server
- npm install
- cd ..
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: gtyeBRyvApRpP7gLGee+IA+1XHvAOq6os/Z5IH00YssJtQvBHu0SkvryGDUqyJSXc8NIdU1SX8ix1TTRdQ6KMBQiveZKvHrDT4WkakxRktGmYCvqMmMczz44xSSobjww3qvlL1K+GwEfl5hCl3FLVRh8J6elJzNrnE8V9kz3WjHlpOhgPO5VNnPcXrCjarsjC+JkiD+/Jl5I2bJoyK3U028wH4KJJfrpMUqVB7T7wLLC8kEmYg9Llvd3S2WwHQYAr1ZmA9qgJ07qI+HfZMFTCxy3In0RrAx7wC85Hmy+t3g9gD0I3kWvKAMm2cJJ705NhuTJI8hZmRHN2aoY43cdb0XDXMtR/nrbmvbcGZi+WVP1YidRgXXyPIAIjxo1FY2Tuvg6Rxgi764K13cktfe00AvZJQHg0OBGPNmSMr/mi/oEVc0N7QMxX57a31S0GbNSsQa03FYr12AOjltLHCo1XxrEEHxC2HuI8spvaKNZ9KDPnmeQB3Uwuwv7S7eGnQpnNgEiUgnnQcVcXm2DmaoJcrxiOvP0CHyxv05kXHbTfAIVjZwI7wZej+lgl0PuhQWp6cK+4cHjzD4LAGdwSCNfSBgl14epl3lvqJMHK/R4SNIX/P1qxHW0EnotvOo3S9fsksq3zfmkReswLSSaG8op4cWMQqm35lIMaTj3roIGcq8=
  app: react-flix-ff
  on:
    repo: Sanny232/reactflix
    branch: master
  skip_cleanup: 'true'
