language: node_js
node_js: 16.10.0
before_install:
- cd server
- npm install
- cd ..
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: EXW6rNtMdxkA3R3EBO3OL6+An8GMaKyIGxXorFjqnqNo10LY9+vnQjS4ThB65tIYxXjgQlurySitYzy/DEGxqGvRaVsSrFKw6n7qHlxG7gmcx4dN12IMC30KpY3rFqq5ZY4EObyeeIHrFVhY2jt6bOe37Zf7n6TLYung2ey3tnzZnptpqvZM22OV3ZBzxaOJj36Np9l6HVqIHFypMWv93nF/2WH2mhRTKmmWPjmMjF8/QIRoQH/+jrfjxVIuw8V3fEjRprWiEJbNGtErirtei+w5M0mk1OdwF/3ppeeOKu6Nimxi0R25axOyi+wrv1Ul4CaMO6hrcrZTTy0dgi3+KIZgwrYyqV86zr0QXDss9XNJW9+Crj3c9jtTzupeFZhE+l8eqcSRlLqCBhVis3HYcQrFf7YkXcgzW7J8V5lFN0tHynrMfSZea+HpqT6rzR8Szsc4YiTS558ECHpvwnIIbQMyKfOXhQH9q740fi+3UOLQkGrburwHl7L3h6Isuk2lhyAikTmLqII3bcYUPwnVm/7tskvYI3jBvvo4A2X/NS0+kowvk8kJwlJ4dW9QHMzXPYFP8GYzrviHBjd/d+YQ8oBQmMapYz6YuDk4dH90fOjnBp2gNDPkEWjr4GwsdZaJZBdNpnqh5Qvo9ZKceKQFv8UNlXVQmHExI0zOBc43PDw=
  app: react-flix-ff
  on:
    repo: Sanny232/reactflix
    branch: master
  skip_cleanup: 'true'
